version: "3.9"

services:
  directus:
    image: directus/directus:11
    container_name: directus_app
    environment:

      - SERVICE_URL_DIRECTUS_8055
      - 'KEY=${KEY:-cAtcwMWDSblXCzw7rvH4lxnTqTMSuAps1}'
      - 'SECRET=${SECRET:-cUXsuXDiWaDBalTbOLzYl6hbOFzNWY9BL}'
      - 'NODE_ENV=${NODE_ENV:-development}'
      - 'LOG_LEVEL=${LOG_LEVEL:-info}'
      - 'TELEMETRY=${TELEMETRY:-false}'
      - 'WEBSOCKETS_ENABLED=${WEBSOCKETS_ENABLED:-true}'
      - 'DB_CLIENT=pg'
      - 'DB_HOST=${DB_HOST:-147.79.111.222}'
      - 'DB_PORT=${DB_PORT:-5432}'
      - 'DB_DATABASE=${DB_DATABASE:-batepalco_dev}'
      - 'DB_USER=${DB_USER:-postgres}'
      - 'DB_PASSWORD=${DB_PASSWORD:-6fsK3PqIP9ZUtVJoVh20yV7XIpRjB1eI}'
      - 'DB_SSL=${DB_SSL:-false}'
      - 'CACHE_ENABLED=${CACHE_ENABLED:-true}'
      - 'CACHE_STORE=${CACHE_STORE:-redis}'
      - 'REDIS=${REDIS:-redis://default:6vqBaMtr1mSEGxbSKsS8jqWifTwxa3CFVJXLGXCKr7qAK7FrQroukwfNLT0Iu61V@147.79.111.222:6379/0}'
      - 'ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}'
      - 'ADMIN_PASSWORD=${ADMIN_PASSWORD:-123@1H}'
      - 'ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL:-15m}'
      - 'REFRESH_TOKEN_TTL=${REFRESH_TOKEN_TTL:-7d}'
      - 'CORS_ENABLED=${CORS_ENABLED:-false}'
      - 'CORS_ORIGIN=${CORS_ORIGIN}'
      - 'CORS_METHODS=${CORS_METHODS:-GET,POST,PATCH,DELETE}'
      - 'CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS:-Content-Type,Authorization}'
      - 'AUTH_PROVIDERS=google'
      - 'AUTH_GOOGLE_DRIVER=openid'
      - 'AUTH_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID:-353113785593-0ienhgeq7khogmf5baqks95opi4psh0m.apps.googleusercontent.com}'
      - 'AUTH_GOOGLE_CLIENT_SECRET=${AUTH_GOOGLE_CLIENT_SECRET:-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}'
      - 'AUTH_GOOGLE_ISSUER_URL=https://accounts.google.com'
      - 'AUTH_GOOGLE_SCOPE=openid email profile'
      - 'AUTH_GOOGLE_IDENTIFIER_KEY=email'
      - 'AUTH_GOOGLE_MODE=session'
      - 'AUTH_GOOGLE_REDIRECT_ALLOW_LIST=${AUTH_GOOGLE_REDIRECT_ALLOW_LIST:-http://127.0.0.1:8055,http://localhost:8055,http://localhost:3000}'
      - 'AUTH_GOOGLE_ICON=google'
      - 'AUTH_GOOGLE_LABEL=Entrar com Google'
      - 'AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION=${AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION:-true}'
      - 'STORAGE_LOCATIONS=r2'
      - 'STORAGE_R2_DRIVER=s3'
      - 'STORAGE_R2_KEY=${STORAGE_R2_KEY:-c25da0a9158444606efad27ffb4290a7}'
      - 'STORAGE_R2_SECRET=${STORAGE_R2_SECRET:-160aa0b5436b61679c4e3f1137f95afc042c65afe797e40106e70e1469de4030}'
      - 'STORAGE_R2_BUCKET=${STORAGE_R2_BUCKET:-batepalco-dev}'
      - 'STORAGE_R2_REGION=${STORAGE_R2_REGION:-auto}'
      - 'STORAGE_R2_ENDPOINT=${STORAGE_R2_ENDPOINT:-https://4703fbfa958a48f8b9a89e3b4cb720f1.r2.cloudflarestorage.com}'
      - 'STORAGE_R2_FORCE_PATH_STYLE=${STORAGE_R2_FORCE_PATH_STYLE:-true}'

    volumes:
      - directus_uploads:/directus/uploads
      - directus_extensions:/directus/extensions
      - ./data:/directus/data
    ports:
      - "8055:8055"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:8055/server/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  directus_uploads:
  directus_extensions:
